banner:
  banner-heading: Pipeline banner Heading Text
  banner-para: Pipeline banner paragraph Text
  banner-image: /images/bms-science-getty-images.png
sthp-content: |-
  #### This is a H4 Heading.

  **This is a normal paragraph with bold.**
tab:
  tab-info:
    - tab-header: Solid Tumor
      tab-body: Solid Tumor Content
    - tab-header: Hematology
      tab-body: Hematology content
