banner:
  banner-heading: Pipeline banner Heading Text
  banner-para: Pipeline banner paragraph Text
  banner-image: /images/bms-science-getty-images.png
sthp-content: |-
  #### This is a H4 Heading Tag

  **This is a normal paragraph Tag with bold.**
tab:
  tab-info:
    - tab-header: Solid Header
      tab-card-container:
        tab-card:
          - card-title: Advanced Solid Tumors
            phase-row:
              - phase-col1: Nivolumab ± ipilimumab
                phase-col2: Anti–PD-1 ± anti–CTLA-4
                phase-col3: Advanced solid tumors
                phase-col4: "1"
                phase-col1-image: /images/bmstrial-1.png
              - phase-col1: Nivolumab ± relatlimab
                phase-col2: Anti–PD-1 ± anti–LAG-3
                phase-col3: Advanced or metastatic solid tumors
                phase-col4: 1/2
          - card-title: Breast
            phase-row:
              - phase-col1: Nivolumab + CDK inhibitor + aromatase inhibitor
                phase-col2: Anti–PD-1 + CDK inhibitor + aromatase inhibitor
                phase-col3: Neoadjuvant ER+/HER2- breast cancer
                phase-col4: 1/3
              - phase-col1: Nivolumab + chemo followed by nivolumab + endocrine therapy
                phase-col2: Anti–PD-1
                phase-col3: Neoadjuvant/adjuvant high-risk breast cancer
                phase-col4: "2"
                phase-col1-image: /images/bmstrial-1.png
      tab-footnote:
        footnote-style1: "Probody™ is a trademark of CytomX Therapeutics, Inc.\r

          \r\n"
        footnote-image-style: "Trial investigates BMS agent(s) in combination with 1 or
          more non–BMS-owned assets. Development partnerships include:\r

          \r\n"
        footnote-list-item: "- First item\r

          - Second item\r

          - Third item"
        footnote-hang: "<span class=\"hang\">*</span>Refers to tumors that are
          non-metastatic or resectable metastatic.\r\n"
        footnote-full: "1L=first line; 1L+=1L and above; 2L=second line; 2L+=2L and
          above; 3L=third line; 3L+=3L and above; 4L=fourth line; 4L+=4L and
          above; ADC=antibody-drug conjugate; ADP=adenosine diphosphate;
          AHR=aryl hydrocarbon receptor; AML=acute myeloid leukemia;
          BCG=bacillus Calmette-Guérin; BCMA=B-cell maturation antigen;
          BCR-ABL=breakpoint cluster region-Abelson; BET=bromodomain and
          extraterminal domain; BRD4=bromodomain containing 4; CAR T=chimeric
          antigen receptor T cells; CCR2/5=chemokine (C-C motif) receptors 2/5;
          cCRT=concurrent chemoradiotherapy; CDK=cyclin-dependent kinase;
          chemo=chemotherapy; CML=chronic myeloid leukemia; CNS=central nervous
          system; CRC=colorectal cancer; CRPC=castration-resistant prostate
          cancer; CTLA-4=cytotoxic T-lymphocyte antigen 4; CTLA-4-NF=CTLA-4
          non-fucosyl; dMMR=mismatch repair deficient; EC=esophageal cancer;
          EGFR=epidermal growth factor receptor; EP4=prostaglandin E2 receptor
          4; ER=estrogen receptor; GBM=glioblastoma multiforme; GC=gastric
          cancer; GEJ=gastroesophageal junction; HCC=hepatocellular carcinoma;
          HER2=human epidermal growth factor receptor 2; IDH2=isocitrate
          dehydrogenase-2; IDO1=indoleamine 2,3-dioxygenase-1;
          Ig=immunoglobulin; IL-2=interleukin-2; IL-8=interleukin-8;
          ITIM=immunoreceptor tyrosine-based inhibitory motif; JAK2=Janus kinase
          2; LAG-3=lymphocyte-activation gene 3; LSD1=lysine-specific histone
          demethylase 1A; mCRC=metastatic CRC; MEK=mitogen-activated protein
          kinase; MGMT=O6-methylguanine-DNA methyltransferase;
          MIBC=muscle-invasive bladder cancer; mNSCLC=metastatic NSCLC;
          MSI-H=microsatellite instability-high; MSS=microsatellite stable;
          NHL=non-hodgkins lymphoma; NK=natural killer; NLRP3=nucleotide-binding
          oligomerization domain-like receptor family, pyrin domain containing
          3; NMIBC=non–muscle-invasive bladder cancer; NSCLC=non–small cell lung
          cancer; PARP=poly (ADP-ribose) polymerase; PD-1=programmed death
          receptor-1; PSCA=prostate stem cell antigen; RCC=renal cell carcinoma;
          R/R=relapsed/refractory; RT=radiotherapy; SCCHN=squamous cell
          carcinoma of the head and neck; SCLC=small cell lung cancer;
          SIRPα=CD47-signal regulatory protein alpha; SLAMF7=signaling
          lymphocytic activation molecule family member 7; STING=stimulator of
          interferon genes; TACE=transarterial chemoembolization; TIGIT=T-cell
          immunoreceptor with Ig and ITIM domains; TIM-3=T-cell immunoglobulin
          mucin-3; TKI=tyrosine kinase inhibitor; TLR8=Toll-like receptor 8;
          TMB-H=tumor mutational burden high; TNBC=triple-negative breast
          cancer; VEGF=vascular endothelial growth factor.\r

          \r\n"
        footnote-image: /images/bmstrial-1.png
    - tab-header: Hematology
      tab-card-container:
        tab-card:
          - card-title: Hematologic Malignancies
            phase-row:
              - phase-col1: Relatlimab
                phase-col2: Anti–LAG-3
                phase-col3: Hematologic malignancies
                phase-col4: 2/3
              - phase-col1: Nivolumab
                phase-col2: Anti–PD-1
                phase-col3: Hematologic malignancies
                phase-col4: "3"
                phase-col1-image: /images/bmstrial-1.png
          - card-title: Myelodysplastic Syndromes
            phase-row:
              - phase-col1: Luspatercept-aamt
                phase-col2: Erythroid maturation agent
                phase-col3: ESA naïve
                phase-col4: 1/2
                phase-col1-image: /images/bmstrial-1.png
              - phase-col1: Azacitidine (CC-486)
                phase-col2: Oral HMA
                phase-col3: Post-HMA failure
                phase-col4: 1/3
      tab-footnote:
        footnote-image-style: "Trial investigates BMS agent(s) in combination with 1 or
          more non–BMS-owned assets. Development partnerships include:\r

          \r\n"
        footnote-list-item: "- Hema First item\r

          - Second item\r

          - Third item"
        footnote-hang: "<span class=\"hang\">*</span>Celgene in collaboration with
          bluebird bio™.\r\n"
        footnote-full: "1L=first line; 1L+=1L and above; 2L=second line; 2L+=2L and
          above; 3L=third line; 3L+=3L and above; 4L=fourth line; 4L+=4L and
          above; ADC=antibody-drug conjugate; AML=acute myeloid leukemia;
          BCMA=B-cell maturation antigen; BCR-ABL=breakpoint cluster
          region-Abelson; BET=bromodomain and extraterminal domain;
          BRD4=bromodomain containing 4; CAR T=chimeric antigen receptor T
          cells; chemo=chemotherapy; CML=chronic myeloid leukemia; CNS=central
          nervous system; CTLA-4=cytotoxic T-lymphocyte antigen 4;
          DNA=deoxyribonucleic acid; ESA=erythropoiesis-stimulating agent;
          GPRC5D=G protein-coupled receptor, class C group 5 member D;
          HMA=hypomethylating agent; ide-cel=idecabtagene vicleucel;
          IDH2=isocitrate dehydrogenase-2; IMiD=immunomodulatory drug;
          JAK2=Janus kinase 2; LAG-3=lymphocyte-activation gene 3;
          liso-cel=lisocabtagene maraleucel; LSD1=lysine-specific histone
          demethylase 1A; MM=multiple myeloma; NEX-T=next-generation CAR-T
          candidates; NHL=non-Hodgkin lymphoma; orva-cel=orvacabtagene
          autoleucel; PD-1=programmed death receptor-1; R/R=relapsed/refractory;
          SIRPα=CD47-signal regulatory protein alpha; SLAMF7=signaling
          lymphocytic activation molecule family member 7; TKI=tyrosine kinase
          inhibitor.\r

          \r\n"
        footnote-image: /images/bmstrial-1.png
