backend:
  name: github
  repo: pixacore-india/BMS-Science
  branch: master

media_folder: "img"

collections: 
  - label: Global,
    name: global,
    files:
      - label: Header
        name: header
        file: _data/header.yml
        fields:
          - label: Logo
            name: logo
            widget: image
          - label: Primary Links
            name: primary-links
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
              - label: Sub Links 
                name: sublinks 
                widget: list
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: Path, name: path, widget: string} 