backend:
  name: github
  repo: pixacore-india/Science
  branch: master

media_folder: "images"

collections: 
  - label: Global
    name: global
    files:
      - label: Header
        name: header
        file: _data/header.yml
        fields:
          - label: Logo
            name: logo
            widget: image
          - label: Primary Links
            name: primary-links
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
              - label: Sub Links 
                name: sublinks 
                widget: list
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: Path, name: path, widget: string} 
      - label: Footer
        name: footer
        file: _data/footer.yml
        fields:
          - label: Footer Links
            name: footer-links
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
          - label: Copyright Text
            name: copyright-text   
            widget: string
          - label: Last Updated
            name: last-update   
            widget: string
          - label: Project Code
            name: project-code   
            widget: string
  - label: pages
    name: pages
    files: 
      - label: Pipeline
        name: pipeline
        file: _data/pipeline.yml
        fields:
          - label: Banner
            name: banner
            widget: object
            fields: 
              - label: Banner Heading
                name: banner-heading
                widget: string
              - label: Banner Paragraph
                name: banner-para
                widget: string
              - label: Banner Image
                name: banner-image
                widget: image
                
          - label: Solid Tumor and Hematology Pipeline Content
            name: sthp-content
            widget: markdown

          - label: Tab
            name: tab
            widget: object  
            fields:
              - lable: Tab Info
                name: tab-info
                widget: list
                fields:
                  - {label: Tab Header, name: tab-header, widget: string}
                  - {label: Tab Filter Container, name: tab-filter-container, widget: object,
                      fields: [
                        {label: Therapeutic Area List, name: therapeutic-area-list, widget: list,
                          fields: [
                            {label: Therapeutic List Item, name: therapeutic-list-item, widget: string}
                          ]
                        },
                        {label: Phase List, name: phase-list, widget: list,
                          fields: [
                            {label: Phase List Item, name: phase-item, widget: string}
                          ]
                        }
                      ]
                    }
                  - {label: Switch Label, name: switch-label, widget: string}
                  - {label: Column Label 1, name: column-label1, widget: string}
                  - {label: Column Label 2, name: column-label2, widget: string}
                  - {label: Column Label 3, name: column-label3, widget: string}   
                  - {label: Tab Card Container, name: tab-card-container, widget: object,
                      fields: [
                        {label: Tab Card, name: tab-card, widget: list,
                          fields: [ 
                            {label: Card Title, name: card-title, widget: string},
                            {label: Phase Row, name: phase-row, widget: list,
                              fields: [
                                {label: Phase Col1 Image, name: phase-col1-image, widget: image, required: false},
                                {label: Phase Col1, name: phase-col1, widget: string},
                                {label: Phase Col2, name: phase-col2, widget: string},
                                {label: Phase Col3, name: phase-col3, widget: string},
                                {label: Phase Col4, name: phase-col4, widget: select, options: ["1", "1/2", "1/3", "2", "2/3", "3"]}
                              ]
                            }   
                          ]
                        }
                      ]
                    } 
                  - {label: Tab Footnote, name: tab-footnote, widget: object, 
                      fields: [ 
                        {label: Footnote Style 1, name: footnote-style1, widget: markdown, required: false},
                        {label: Footnote Image, name: footnote-image, widget: image, required: false},
                        {label: Footnote Style with Image, name: footnote-image-style, widget: markdown, required: false},
                        {label: Footnote Style with List Item, name: footnote-list-item, widget: markdown, required: false},
                        {label: Footnote Hang style, name: footnote-hang, widget: markdown, required: false},
                        {label: Footnote Full, name: footnote-full, widget: markdown, required: false}
                      ]
                    }
                                     
            
      - label: Resources
        name: resources
        file: _data/resources.yml
        fields:
          - label: Resource Heading
            name: resource-heading
            widget: string
          - label: Resource Thumbnail
            name: resource-thumbnail
            widget: list
            fields:
              - {label: Thumb Type, name: thumb-type, widget: select, options: ["Download File"]}
              - {label: Thumb Image, name: thumb-image, widget: image}
              - {label: Thumb Heading, name: thumb-head, widget: string}  
              - {label: Thumb URL, name: thumb-url, widget: string}  
              - {label: Thumb Button Text, name: thumb-button, widget: string}        

