backend:
  name: github
  repo: pixacore-india/BMS-Science
  branch: master

media_folder: "images"

collections: 
  - label: Global
    name: global
    files:
      - label: Header
        name: header
        file: _data/header.yml
        fields:
          - label: Logo
            name: logo
            widget: image
          - label: Primary Links
            name: primary-links
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
              - label: Sub Links 
                name: sublinks 
                widget: list
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: Path, name: path, widget: string} 
      - label: Footer
        name: footer
        file: _data/footer.yml
        fields:
          - label: Footer Links
            name: footer-links
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
          - label: Copyright Text
            name: copyright-text   
            widget: string
          - label: Last Updated
            name: last-update   
            widget: string
          - label: Project Code
            name: project-code   
            widget: string
  - label: pages
    name: pages
    files: 
      - label: Pipeline
        name: pipeline
        file: _data/pipeline.yml
        fields:
          - label: Banner
            name: banner
            widget: object
            fields: 
              - label: Banner Heading
                name: banner-heading
                widget: string
              - label: Banner Paragraph
                name: banner-para
                widget: string
              - label: Banner Image
                name: banner-image
                widget: image

          - label: Footnote Section
            name: footnote-section
            widget: object
            fields:
              - label: Footnote Style 1
                name: footnote-style1
                widget: markdown
              - label: Footnote Style with Image
                name: footnote-image-style
                widget: markdown
              - label: Footnote Style with List Item
                name: footnote-list-item
                widget: markdown
              - label: Footnote Hang style
                name: footnote-hang
                widget: markdown
              - label: Footnote Full
                name: footnote-full
                widget: markdown        
                
          - label: Solid Tumor and Hematology Pipeline Content
            name: sthp-content
            widget: markdown
            
      - label: Resources
        name: resources
        file: _data/resources.yml
        fields:
          - label: Resource Heading
            name: resource-heading
            widget: string
          - label: Resource Thumbnail
            name: resource-thumbnail
            widget: list
            fields:
              - {label: Thumb Type, name: thumb-type, widget: select, options: ["Download File"]}
              - {label: Thumb Image, name: thumb-image, widget: image}
              - {label: Thumb Heading, name: thumb-head, widget: string}  
              - {label: Thumb URL, name: thumb-url, widget: string}  
              - {label: Thumb Button Text, name: thumb-button, widget: string}        

