backend:
  name: github
  repo: pixacore-india/BMS-Science
  branch: master

media_folder: "images"

collections: 
  - label: Global
    name: global
    files:
      - label: Header
        name: header
        file: _data/header.yml
        fields:
          - label: Logo
            name: logo
            widget: image
          - label: Primary Links
            name: primary-links
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
              - label: Sub Links 
                name: sublinks 
                widget: list
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: Path, name: path, widget: string} 
      - label: Footer
        name: footer
        file: _data/footer.yml
        fields:
          - label: Footer Links
            name: footer-links
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
          - label: Copyright Text
            name: copyright-text   
            widget: string
          - label: Last Updated
            name: last-update   
            widget: string
          - label: Project Code
            name: project-code   
            widget: string               